[tools]
aws-cli = 'latest'
bat = 'latest'
bat-extras = 'latest'
babashka = 'latest'
bazelisk = 'latest'
bazel-watcher = 'latest'
docker-compose = 'latest'
docker-cli = 'latest'
lua = 'latest'
"cargo:eza" = 'latest'
java = 'latest'
fd = 'latest'
cabal = 'latest'
clojure = 'latest'
clj-kondo = 'latest'
ghc = '9.6.7'
ghcup = 'latest'
github-cli = 'latest'
node = 'latest'
yarn = 'latest'
ruby = '3.1.5'
rust = 'latest'
cargo-make = 'latest'
rlwrap = {version = 'latest', os = ["macos"]}
go = 'latest'
saml2aws = 'latest'
python = '3'
pipx = 'latest'
jq = 'latest'
neovim = 'latest'
maven = 'latest'
opam = 'latest'
overmind = {version = 'latest', os = ["macos"]}
ripgrep = 'latest'
ripgrep-all = 'latest'
terraform = 'latest'
tmux = 'latest'
uv = 'latest'
"pipx:dbt-core" = { version = "1.10.*", uvx_args = "--with dbt-postgres==1.10.*" }


[settings]
idiomatic_version_file_enable_tools = ["ruby"]
